export const metadata = {
  title: {
    absolute: "About Khursheed",
  },
  description: "Generated by Next.js",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
